io:
  outputs_root: outputs
  progress: true

data:
  symbols: [BTCUSDT]
  bars_dir: inputs/bars_1m
  ticks_dir: inputs/ticks
  bar_schema: auto
  file_patterns:
    bars: "{SYMBOL}/{SYMBOL}-1m-{YYYY}-{MM}.csv"
    ticks: "{SYMBOL}/{SYMBOL}-ticks-{YYYY}-{MM}.csv"
  months: { start: "2025-01", end: "2025-08" }

walkforward:
  train_months: 6
  test_months: 1
  step_months: 1
  progress: true

features:
  atr_n: 14
  donch_n_candidate: 20
  percentiles_fit_on: train
  base_features:
    - t_240; t_60; t_15; accel_15_240
    - atr; dcw; atr_p; dcw_p
    - body_dom; close_to_hi_atr; close_to_lo_atr
  nonlinear:
    enabled: true
    windows: { small: 15, mid: 60 }
    include:
      - convexity_15_60_240
      - trend_agree_15_60
      - trend_agree_60_240
      - trend_ratio_15_60
      - squeeze_score
      - squeeze_age
      - release_slope_15
      - impulse_near_high
      - impulse_near_low
      - zcr_60
      - sign_entropy_60
      - rv60_over_atr
      - range_ratio_60
      - volofvol_proxy
    age_for_nonlinear: true
  age:
    enabled: true
    n_bins_feature: 5
    n_bins_age: 6
    occ_windows: [60, 240]
    save_schema: true
    schema_file: "artifacts/quantiles.json"

candidates:
  mode: blind
  blind:
    thinning:
      type: cusum_by_ret
      params:
        ret_lookback: 240
        k_sigma: 1.30
        drift: 0.0
        min_gap_bars: 5            # was 15 → allow closer distinct impulses
        fallback_stride_k: 10       # sample a secondary anchor to pick up near-misses
    sides: both
  vol_prefilter: null           # remove volatility gate

labels:
  r_mult: 5
  horizon_hours: 480
  non_overlap: true
  non_overlap_policy: quick     # quick ignition policy
  quick_ignition_hours: 2        # 30 minutes per side
  intra_bar_epsilon_ms: 1
  min_risk_atr_frac: 0.001
  eta_atr: 20.0
  # sane eta mapping
  eta_by_atr_p: []
  eta_cap: { min: 2.50, max: 20.00 }
  time_scale_from_eta: { base_eta: 2.50, clamp: [0.75, 10.0] }
  stop_band_atr: 0.05
  no_ticks_policy: skip

# Optional knobs the deduper will read (defaults shown)
dedupe:
  scope: side                  # 'side' or 'symbol'
  rank_by: eta_proxy_then_atr  # eta proxy, then atr_p, then earliest ts

mining:
  rules:
    auto_binning: true
    n_bins_cont: 5
    max_terms: 2
    top_k: 60
    min_support: 24
    min_support_frac: 0.001        # was 0.002 → ~11–12 samples at n_train≈11.5k
    min_months: 4
    min_wins: 4
    precision_include_timeouts: false
    min_resolve_frac: 0.25           # avoid timeout-heavy rules
    min_resolve_uplift_pp: 0.0
    min_precision_uplift_pp: 0.0
    min_lift_lcb: 0.0
    max_timeout_rate: 0.60           # drop rules with >60% timeouts
    wilson_z: 1.96
    mine_losers: true
    loser_top_k: 8
    loser_max_precision_ucb: 0.35
    loser_min_resolve_frac: 0.40
    loser_min_months: 2
    fdr: { enabled: true, alpha: 0.10 }

loser_mask:
  enabled: true
  min_support: 20
  min_months_with_lift: 2
  min_ppv_lcb: 0.55
  save_artifact: true

gate:
  mode: ml
  calibration: isotonic
  target_ppv_lcb: 0.70
  min_coverage: 0.02
  val_months: 1
  crosses_cap: 20

ml_gating:
  enabled: true
  model: logreg
  calibration: isotonic
  target_ppv: 0.70
  min_coverage: 0.02
  val_months: 1
  crosses_cap: 20
  regime_gate: true
  regime_min_age_bin: 4
  regime_occ_windows: [240]
  features:
    include_prefixes: ["qbin_", "qbin_agebin_", "agebin_", "since_", "occ_", "B_"]
    exclude_prefixes: []
  n_bins_cont: auto
  binning:
    candidates: [3, 4, 5, 7, 10]
    min_bin_frac: 0.005
    mi_delta_min: 0.002
    ece_delta_min: 0.002
    max_js_month_drift: 0.15
    prefer_monotone: true

execution_sim:
  fees:
    maker_bps: 1.0
    taker_bps: 5.0
    entry_is_maker: false
    exit_is_maker: true
  funding:
    enabled: true
    rate_per_hour: 0.0001
    sign: 1.0
  inventory:
    enable: false

tests:
  parity:
    enabled: false
    signals_ref_csv: null
    trades_ref_csv: null
    r_tol: 0.02
    max_signal_mismatch: 0
